development:
  adapter: postgresql
  encoding: unicode
  database: hr_workspace
  pool: 5
  username: user
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hr_workspace
  pool: 5
  username: user
  password:
